# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipestep',
            name='step_description',
            field=models.CharField(max_length=40000),
        ),
    ]
