# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20160402_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='website',
            field=models.CharField(max_length=5000),
        ),
    ]
