# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-25 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_auto_20200625_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='meat',
            field=models.CharField(choices=[(b'V', b'Veggie'), (b'T', b'Tofu'), (b'C', b'Chicken'), (b'F', b'Fish'), (b'B', b'Beef'), (b'P', b'Pork'), (b'VEGAN', b'Vegan')], max_length=5),
        ),
    ]
